### ISSUE TITLE
1.3.2 - installation from source fails

### ISSUE THREAD

**Issue by ckchow** [sarugaku/shellingham#34]
```
pip install --no-binary=shellingham shellingham==1.3.2
Collecting shellingham==1.3.2
  Downloading https://files.pythonhosted.org/packages/4b/f0/39516ebeaca978d6607609a283b15e7637622faffc5f01ecf78a49b24cd5/shellingham-1.3.2.tar.gz
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/cchow/.pyenv/versions/3.6.6/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/jz/ml8h8ykd55zfpzgrd04qc53h0000gn/T/pip-install-pka7dnps/shellingham/setup.py'

    ----------------------------------------
```

**Comment by uranusjr** [comment]
What version of pip are you using? I believe this is only an issue with old pip versions.

**Comment by dciborow** [comment]
I am seeing this issue with pip 18.1.

I can't control the pip version on the build server, so particularly problematic for me right now.
